issuer: http://localhost:8000
listen: ":8000"

sign_key: /path/to/jwt-sign.key

ldap:
  server: ldap://ldap.example.com
  base_dn: OU=somewhere,DC=example,DC=local
  id_attribute: sAMAccountName
  disable_tls: false

tls:
  cert: /path/to/tls.crt
  key: /path/to/tls.key

template:
  login_page: /path/to/login-template.html
  error_page: /path/to/error-template.html

expire:
  login: 1h
  code: 5m
  token: 1d
  refresh: 7d
  sso: 14d

endpoint:
  authorization: /login
  token: /login/token
  userinfo: /login/userinfo
  jwks: /login/certs

scope:
  profile:
    - claim: name
      attribute: displayName
    - claim: given_name
      attribute: givenName
    - claim: family_name
      attribute: sn

  email:
    - claim: email
      attribute: mail

  phone:
    - claim: phone_number
      attribute: telephoneNumber

  groups:
    - claim: groups
      attribute: memberOf
      type: '[]string'

client:
  http://example.com:
    secret: $2y$05$ctB3fgxdzGEXICdJCsb1qOkl3169uhjq0UC5vFQa7o.yWE69vJccC # secret key that hash by `ldapin gen-client` command
    redirect_uri:
      - http://example.com/login/*
      - http://*.example.com/**

disable_client_auth: false

metrics:
  path: /metrics
  username: prometheus-user
  password: password for basic auth
