issuer: http://localhost:8000
listen: ":8000"

# TODO: Support those options
#
#sign_key: /path/to/jwt-sign.key
#
#ldap:
#  server: ldap://ldap.example.com
#  base_dn: OU=somewhere,DC=example,DC=local
#  id_attribute: sAMAccountName
#  disable_tls: false
#
#tls:
#  cert: /path/to/tls.crt
#  key: /path/to/tls.key
#
#template:
#  login_page: /path/to/login-template.html
#  error_page: /path/to/error-template.html
#

ttl:
  code: 10m
  token: 1h

endpoint:
  base_path: /
  authorization: /login
  token: /login/token
  userinfo: /login/userinfo
  jwks: /login/certs

scope:
  profile:
    - claim: name
      attribute: displayName
    - claim: given_name
      attribute: givenName
    - claim: family_name
      attribute: sn

  email:
    - claim: email
      attribute: mail

  phone:
    - claim: phone_number
      attribute: telephoneNumber

  groups:
    - claim: groups
      attribute: memberOf
      type: '[]string'
