issuer = "http://localhost:{{ .Port }}"
listen = "127.0.0.1:{{ .Port }}"

[expire]
login = "30m"
code = "1m"
token = "1h"
refresh = "6h"
sso = "10m"

[endpoint]
authorization = "/authz"
token = "/token"
userinfo = "/userinfo"
jwks = "/certs"
logout = "/logout"

[client.some_client_id]
secret = "$2a$10$gKOvDAJeJCtoMW8DeLdxuOH/tqd2FxsM6hmupzZTW0XsiQhe282Te"  # hash of "secret for some-client"

redirect_uri = [
  "http://some-client.example.com/callback",
  "http://some-client.example.com/logout",
]

allow_implicit_flow = false

request_key = """
{{ .SomeClientPublicKey }}
"""

[client.implicit_client_id]
secret = "$2a$10$iy8gnu3fTEi2Ge8ysOjBEOz2Or8.eBfQV3A7XaxCbZ7GaDlSTBDh2"  # hash of "secret for implicit-client"

redirect_uri = [
  "http://implicit-client.example.com/callback",
  "http://implicit-client.example.com/logout",
]

cors_origin = [
  "http://implicit-client.example.com",
  "http://*.implicit-client.example.com",
]

allow_implicit_flow = true

request_key = """
{{ .ImplicitClientPublicKey }}
"""
