[ldap]
id_attribute = "uid"


[client.some_client]

name = "Example Client"
icon_url = "http://placehold.it/100x100"

# client_secret is "kVnjSa4DHjO-Os5ICXvuP_aFE4JCelGFkbNaGixXo2n1AYWVsqxEpmVOwmfa4lRCBE-y..ZoC7eoWB_PrKxwAOGG8.Tbh51eDw08"
secret = "$2a$10$gobUHsL8fedoDu3AhJCkq.H5iNsq8qc.zbtis0XFOnFH8EiwQc4oi"

redirect_uri = [
  "http://localhost:*",
  "http://localhost:*/**",
]
