name: Security

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '42 15 * * 6'

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: go
      - uses: github/codeql-action/analyze@v1
