name: Security

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '42 15 * * 6'

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: 
          - go

    steps:
    - uses: actions/checkout@v2

    - uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - uses: github/codeql-action/analyze@v1
